name: open-ai-search

services:
  server:
    image: ghcr.io/lucienshui/open-ai-search:main
    ports:
      - "${PORT:-8000}:8000"
    restart: unless-stopped
    command:
      - "--workers"
      - "4"
    environment:
      ENV: "prod"
    env_file:
      - .env
