openai:
  model: "gpt-3.5-turbo"
  api_key: "sk-***"
  base_url: "https://api.openai.com/v1"

search:
  max_results: 30

bing_search_base_url: "https://www.bing.com"  # https://cn.bing.com
bing_search_max_result_cnt: 20

bing_api_subscription_key: "***"
bing_api_mkt:  # https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/reference/market-codes
