port: 8000
workers: 1

openai_model: "gpt-3.5-turbo"
openai_api_key: "sk-***"
openai_base_url: "https://api.openai.com/v1"

bing_search_base_url: "https://www.bing.com"  # https://cn.bing.com
bing_search_max_result_cnt: 20